title: 'UCSF Wynton HPC Cluster'
theme: jekyll-theme-minimal

google_analytics: UA-128646955-1

cluster:
  name: "Wynton"
  version: "1.0"
  
login:
  name: "wynlog2"
  hostname: "log2.wynton.ucsf.edu"
  ip: "169.230.134.15"
devel:
  name: "qb3-dev3"
  hostname: "qb3-dev3"
  ip: "172.26.32.8"
transfer:
  name: "dt2"
  hostname: "dt2.wynton.ucsf.edu"
  ip: "172.26.1.17"

login1:
  name: "wynlog1"
  hostname: "log1.wynton.ucsf.edu"
  ip: "169.230.126.77"
login2:
  name: "wynlog2"
  hostname: "log2.wynton.ucsf.edu"
  ip: "169.230.134.15"
dev1:
  name: "qb3-dev1"
  hostname: "qb3-dev1"
  ip: "172.26.32.2"
dev2:
  name: "qb3-dev2"
  hostname: "qb3-dev2"
  ip: "172.26.32.7"
dev3:
  name: "qb3-dev3"
  hostname: "qb3-dev3"
  ip: "172.26.32.8"
gpudev1:
  name: "qb3-gpudev1"
  hostname: "qb3-gpudev1"
  ip: "172.26.32.3"
transfer1:
  name: "dt1"
  hostname: "dt1.wynton.ucsf.edu"
  ip: "169.230.126.58"
transfer2:
  name: "dt2"
  hostname: "dt2.wynton.ucsf.edu"
  ip: "172.26.1.17"

specs:
  nodes: 339
  physical_cores: 7228
  gpu_nodes: 38
  gpus: 132
  communal_gpu_nodes: 7
  communal_gpus: 24
  
  ## RAM [GiB]:
  ram_min: 48
  ram_max: 768
  
  ## Disk /swap [GiB]:
  swap_min: 4
  swap_max: 4

  ## Local /tmp [GiB]:
  local_tmp_size_min: 4
  local_tmp_size_max: 8

  ## Local /scratch [TiB]:
  local_scratch_size_min: 0.1
  local_scratch_size_max: 1.8
  
  ## Global /wynton/scratch [TiB]:
  global_scratch_size_total: 492
  
  ## NetApp home [TiB]:
  netapp_home_size_total: 20
  
  ## User home [TiB]:
  home_size_total: 383

  ## Group home [TiB]:
  group_size_total: 3800

  ## Job queues
  pu_total: 20185
  member_q_total: 6735

  ## Deprecated fields - use above instead /HB 2019-03-11
  cpu_min: 2.0
  cpu_max: 3.4
  cpu_range: "2.6-3.4 GHz"
  ram_range: "48-768 GiB"
  swap_range: "4 GiB"
  local_tmp_size: "4 GiB"
  local_scratch_size_range: "0.1-1.8 TiB"
  global_scratch_size: "492 TiB"
  netapp_home_size: "20 TiB"
  home_size: "383 TiB"

users:
  nbr_of_accounts: 733
  
assets:
  status_root_path: "https://raw.githubusercontent.com/UCSF-HPC/wynton-slash/master/wynton/docs"

plugins:
  - jekyll-target-blank
